# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Avatar.destroy_all
UserAvatar.destroy_all
user0 = User.create(name: 'Andres Manco', username: 'andresmanco', email: 'andresmanco@gmail.com', password: 'password')
user1 = User.create(name: 'Alvaro De La Torre', username: 'alvarodelatorre', email: 'alvarodelatorre@gmail.com', password: 'password')
user2 = User.create(name: 'Ryan Chan', username: 'ryanchan', email: 'ryanchan@gmail.com', password: 'password')
user3 = User.create(name: 'Jhon Daise', username: 'jhondaise', email: 'jhondaise@gmail.com', password: 'password')
user4 = User.create(name: 'Josh Miller', username: 'joshmiller', email: 'joshmiller@gmail.com', password: 'password')
user5 = User.create(name: 'Ayana Cotton', username: 'ayanacotton', email: 'ayanacotton@gmail.com', password: 'password')
user6 = User.create(name: 'Sydney Barlow', username: 'sydneybarlow', email: 'sydneybarlow@gmail.com', password: 'password')
user7 = User.create(name: 'Emily Collins', username: 'emilycollins', email: 'emilycollins@gmail.com', password: 'password')
user8 = User.create(name: 'Ruby Weiner', username: 'rubyweiner', email: 'rubyweiner@gmail.com', password: 'password')
user9 = User.create(name: 'Juan Simosa', username: 'juansimosa', email: 'juansimosa@gmail.com', password: 'password')
user10 = User.create(name: 'Michael Ortega', username: 'michaelortega', email: 'michaelortega@gmail.com', password: 'password')
user11 = User.create(name: 'Emma Sargeant', username: 'emmasargeant', email: 'emmasargeant@gmail.com', password: 'password')
user12 = User.create(name: 'Fernando Perez', username: 'fernandoperez', email: 'fernandoperez@gmail.com', password: 'password')
user13 = User.create(name: 'Mariana Larez', username: 'marianalarez', email: 'marianalarez@gmail.com', password: 'password')
user14 = User.create(name: 'Christian Martinez', username: 'christianmartinez', email: 'christianmartinez@gmail.com', password: 'password')
user15 = User.create(name: 'Genesis Pacocano', username: 'genesispacocano', email: 'genesispacocano@gmail.com', password: 'password')
user16 = User.create(name: 'Jose Godoy', username: 'josegodoy', email: 'josegodoy@gmail.com', password: 'password')
user17 = User.create(name: 'Rey De La Hoz', username: 'reydelahoz', email: 'reydelahoz@gmail.com', password: 'password')
user18 = User.create(name: 'Anthony Costa', username: 'anthonycosta', email: 'anthonycosta@gmail.com', password: 'password')
user19 = User.create(name: 'Abner Colmenares', username: 'abnercolmenares', email: '@abnercolmenaresgmail.com', password: 'password')
user20 = User.create(name: 'Franco Martinez ', username: 'francomartinez', email: 'francomartinez@gmail.com', password: 'password')


avatar1 = Avatar.create(name:"Boo",image:'http://www.scrollboss.illmosis.net/customsprite/nightslashers-fgtsze_zombieguts_stand1.png',description:"Ghost with the most clicks")
avatar2 = Avatar.create(name: "Slicer",image:'http://www.scrollboss.illmosis.net/comicedits/cyclops-fgtsze_classic_fgtstance-konamiarc.png',description:"Slicing his way to your heart")
avatar3 = Avatar.create(name: "clickMaster",image:'http://www.scrollboss.illmosis.net/comicedits/taskmaster-capfgt_capstand.png',description:"click faster")
avatar4 = Avatar.create(name:"Master Typer",image: 'http://www.scrollboss.illmosis.net/comicedits/modok-fgtsze_mvc3_hover1.png',description:"Typing past the speed of light")
avatar5 = Avatar.create(name:"Bombo",image:'http://www.scrollboss.illmosis.net/customsprite/bomberman-capfgt_holdbomb1_wht.png',description:"He brings the boom")
avatar6 = Avatar.create(name:"Jumbo",image:'http://www.scrollboss.illmosis.net/customsprite/loz-fgtsize_ganon-v1_menace1.png',description: "Large and in charge")
avatar7 = Avatar.create(name:"Winder",image:'http://www.scrollboss.illmosis.net/comicedits/tmnt-fgtsze_caseyjones_pm80s_stand1.png',description:"All wound up and ready to go")
avatar8 = Avatar.create(name:"Js Pro",image:'http://www.scrollboss.illmosis.net/comicedits/groot-fgtsze_bigbare_tta13p1_iamgroot.png',description: "Coding is all he knows")
avatar9 = Avatar.create(name:"Ctrl-alt-del",image:'http://www.scrollboss.illmosis.net/comicedits/ultron-fgtsze_80s_mu88gammill.png',description: "He's here to escape before it breaks")
avatar10 = Avatar.create(name: "faster-better-stronger",image:'http://www.scrollboss.illmosis.net/comicedits/cyborg-fgtsze_v1_standcalm1.png',description:"Working better doing makes it...")
avatar11 = Avatar.create(name: "Soooo goood",image: 'http://www.scrollboss.illmosis.net/comicedits/batman-fgtsze_comic_70s80s_standcalm-lookcamera.png',description: " He's just that good")
avatar12 = Avatar.create(name: "Fastest-Fingers-in-the-West",image:'http://www.scrollboss.illmosis.net/comicedits/mrfreeze-fgtsze_btaslike_ready1.png',description:"Outlaw with nothing to lose")
avatar13 = Avatar.create(name: "Soooo bad",image:'http://www.scrollboss.illmosis.net/comicedits/blackmanta-fgtsze_classic_pose1.png',description: " He's just that bad")
avatar14 = Avatar.create(name: "Pretty",image:'http://www.scrollboss.illmosis.net/customsprite/splatterhouse-fgtsze_hellchaos_head-mid.png',description: "Yeah...pretty Ugly!" )
avatar15 = Avatar.create(name: "Garish",image:'http://www.scrollboss.illmosis.net/customsprite/sfa-joe_blanka_stand.png',description: "I don't know")
avatar16 = Avatar.create(name: "Slammer",image:'http://www.scrollboss.illmosis.net/customsprite/ffight-capfgt_rolento-sfa_edit-sfa2endingp1.png',description: "He brings the pow")
avatar17 = Avatar.create(name:"ZOmbie",image:'http://www.scrollboss.illmosis.net/customsprite/residentevil-fgtsze_zombieclassic_stand01.png',description: "Undead and ready to rock")
avatar18 = Avatar.create(name:"Robotomungo",image:'http://www.scrollboss.illmosis.net/customsprite/sonic-fgtsze_eggman-classic_handsonhips.png',description: "He's pretty much a robot-cyborg-superHero or something")
avatar19 = Avatar.create(name: "rebOOt",image:'http://www.scrollboss.illmosis.net/customsprite/ninjagaiden-fgtsze_pumpkinhead_knife_stand.png',description: "he reboots")
avatar20 = Avatar.create(name:"Moon Master",image:'http://www.scrollboss.illmosis.net/customsprite/ninjagaiden-fgtsze_pumpkinhead_knife_stand.png',description: " Your the moon master")

UserAvatar.create(user_id: user1.id, avatar_id: avatar20.id)
UserAvatar.create(user_id: user2.id, avatar_id: avatar19.id)
UserAvatar.create(user_id: user3.id, avatar_id: avatar18.id)
UserAvatar.create(user_id: user4.id, avatar_id: avatar17.id)
UserAvatar.create(user_id: user5.id, avatar_id: avatar18.id)
UserAvatar.create(user_id: user6.id, avatar_id: avatar16.id)
UserAvatar.create(user_id: user7.id, avatar_id: avatar15.id)
UserAvatar.create(user_id: user8.id, avatar_id: avatar14.id)
UserAvatar.create(user_id: user9.id, avatar_id: avatar13.id)
UserAvatar.create(user_id: user10.id, avatar_id: avatar12.id)
UserAvatar.create(user_id: user11.id, avatar_id: avatar11.id)
UserAvatar.create(user_id: user12.id, avatar_id: avatar10.id)
UserAvatar.create(user_id: user13.id, avatar_id: avatar9.id)
UserAvatar.create(user_id: user14.id, avatar_id: avatar8.id)
UserAvatar.create(user_id: user15.id, avatar_id: avatar7.id)
UserAvatar.create(user_id: user16.id, avatar_id: avatar6.id)
UserAvatar.create(user_id: user17.id, avatar_id: avatar5.id)
UserAvatar.create(user_id: user18.id, avatar_id: avatar4.id)
UserAvatar.create(user_id: user19.id, avatar_id: avatar3.id)
UserAvatar.create(user_id: user20.id, avatar_id: avatar2.id)
UserAvatar.create(user_id: user1.id, avatar_id: avatar1.id)
UserAvatar.create(user_id: user2.id, avatar_id: avatar2.id)
UserAvatar.create(user_id: user3.id, avatar_id: avatar5.id)
UserAvatar.create(user_id: user4.id, avatar_id: avatar8.id)
UserAvatar.create(user_id: user5.id, avatar_id: avatar10.id)
UserAvatar.create(user_id: user6.id, avatar_id: avatar15.id)
UserAvatar.create(user_id: user7.id, avatar_id: avatar13.id)
UserAvatar.create(user_id: user8.id, avatar_id: avatar2.id)
UserAvatar.create(user_id: user0.id, avatar_id: avatar3.id)
UserAvatar.create(user_id: user0.id, avatar_id: avatar5.id)
UserAvatar.create(user_id: user0.id, avatar_id: avatar7.id)
UserAvatar.create(user_id: user0.id, avatar_id: avatar9.id)
